apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: jenkins
  type: LoadBalancer
  loadBalancerIP: 10.64.35.208
---
apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: bibinwilson/priveleged-jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
              - name: jenkins
                mountPath: /var/jenkins_home
      volumes:
      - name: jenkins
        persistentVolumeClaim:
           claimName: jenkins-pvc
